"""RU localization of Dreame Vacuum persistent notifications (HRYNdev fork).

Isolated translation layer: upstream code is untouched except one call in
coordinator.py. Maps the integration's hardcoded English notification texts to
Russian by exact substring replacement (longest-first to avoid partial hits).
Unknown/new strings fall through unchanged (English), so updates never break.
"""

TRANSLATIONS = {
    "1. Turn robot over with the bottom facing up. Press the release button on one side of the roller mop to take it out, then clean any debris around it.\n2. Press the orange clip and take out the fluffing roller. Clean any hair or debris on it.\n3. After cleaning, install the fluffing roller and press the clip firmly. Then install the roller mop, place the robot flat, and resume the task.\nIf the issue persists, please check more details or contact customer service.": "1. Переверните робота вверх дном. Нажмите кнопку фиксатора с одной стороны валиковой салфетки, чтобы извлечь её, затем очистите мусор вокруг.\n2. Нажмите оранжевый зажим и извлеките ворсовый валик. Удалите с него волосы и мусор.\n3. После очистки установите ворсовый валик и плотно прижмите зажим. Затем установите валиковую салфетку, поставьте робота ровно и возобновите задачу.\nЕсли проблема не исчезла, ознакомьтесь с подробностями или обратитесь в службу поддержки.",
    "Please check the dock and try the following steps:\n1. Make sure the hatch is fully closed.\n2. Make sure the three groups of mops are placed on the hatch in red-yellow-blue order. If the mops are currently on the transport carrier or washboard, put them back on the hatch in this order and try again.\n3. Check for any debris inside the dock. Do not place your hand, robot, or other items in the washboard when switching mops.": "Проверьте док-станцию и выполните следующие шаги:\n1. Убедитесь, что крышка полностью закрыта.\n2. Убедитесь, что три комплекта салфеток установлены на крышке в порядке красный-жёлтый-синий. Если салфетки сейчас находятся на транспортной каретке или скребковой панели, верните их на крышку в этом порядке и повторите попытку.\n3. Проверьте, нет ли мусора внутри док-станции. Не помещайте руку, робота или другие предметы в зону мойки во время замены салфеток.",
    "Edge mop stopped rotating. Please follow these steps:\n1. Check if robot is on a carpet. Friction between the edge mop and carpet may stop it from rotating. Move robot to a non-carpet area and resume cleaning.\n2. Check if the edge mop is tangled. If so, remove them and resume cleaning.": "Краевая салфетка перестала вращаться. Выполните следующие шаги:\n1. Проверьте, не находится ли робот на ковре. Трение между краевой салфеткой и ковром может остановить вращение. Переместите робота на участок без ковра и возобновите уборку.\n2. Проверьте, не намоталось ли что-то на краевую салфетку. Если да, удалите и возобновите уборку.",
    "Please check the dock and try the following steps:\n1. Please manually attach the mop that needs washing to robot.\n2. Please install other dirty mops onto the hatch.\n3. Go to the app → Dock Functions → Wash to restart the mop-washing task.": "Проверьте док-станцию и выполните следующие шаги:\n1. Вручную закрепите на роботе салфетку, которую нужно вымыть.\n2. Установите остальные грязные салфетки на крышку.\n3. Перейдите в приложение → Функции док-станции → Мойка, чтобы перезапустить мойку салфеток.",
    "Check for any debris near the roller mop and mop cover. Clean the roller mop to prevent the cover from getting stuck. After that, place the robot flat and resume the task. If the issue persists, please contact customer service.": "Проверьте, нет ли мусора рядом с валиковой салфеткой и её крышкой. Очистите валиковую салфетку, чтобы крышка не заклинивала. После этого поставьте робота ровно и возобновите задачу. Если проблема не исчезла, обратитесь в службу поддержки.",
    "Check for any debris near the roller mop and mop cover. Clean the roller mop to prevent it from getting stuck. After that, place the robot flat and resume the task. If the issue persists, please contact customer service.": "Проверьте, нет ли мусора рядом с валиковой салфеткой и её крышкой. Очистите валиковую салфетку, чтобы она не заклинивала. После этого поставьте робота ровно и возобновите задачу. Если проблема не исчезла, обратитесь в службу поддержки.",
    "Please check the base station.\n1. Check if the ramp extension plate is installed down to the base station;\n2. Check if the base station is powered on;\n3. Make sure there is no obstacle in front of the base station.": "Проверьте базовую станцию.\n1. Проверьте, опущена ли и установлена ли пандусная накладка на базовой станции;\n2. Проверьте, включена ли базовая станция;\n3. Убедитесь, что перед базовой станцией нет препятствий.",
    "Robot stuck at the step/threshold\n1. Please move robot to an open area and restart the task.\n2. It is recommended to set the step/threshold as an impassable threshold to prevent robot from getting stuck.": "Робот застрял на ступеньке или пороге\n1. Переместите робота на свободное место и перезапустите задачу.\n2. Рекомендуем отметить эту ступеньку или порог как непроходимый, чтобы робот больше не застревал.",
    "Robot stuck among the tables and chairs\n1. Please move robot to an open area and restart the task.\n2. It is recommended to arrange the tables and chairs neatly to prevent robot from getting stuck.": "Робот застрял среди столов и стульев\n1. Переместите робота на свободное место и перезапустите задачу.\n2. Рекомендуем аккуратно расставить столы и стулья, чтобы робот больше не застревал.",
    "Robot stuck in the narrow passage\n1. Please move robot to an open area and restart the task.\n2. It is recommended to set the narrow passage as a no-go zone to prevent the robot from getting stuck.": "Робот застрял в узком проходе\n1. Переместите робота на свободное место и перезапустите задачу.\n2. Рекомендуем отметить узкий проход как запретную зону, чтобы робот больше не застревал.",
    "Washboard stops working. Please follow troubleshooting steps as below:\n1. Check if the washboard is tangled. Clean up before use\n2. Check if the washboard is installed properly\n3.如仍未解决请联系客服": "Скребковая панель перестала работать. Выполните следующие шаги по устранению неполадки:\n1. Проверьте, не намоталось ли что-то на скребковую панель. Очистите перед использованием\n2. Проверьте, правильно ли установлена скребковая панель\n3. Если проблема не исчезла, обратитесь в службу поддержки",
    "Robot stuck in a low-clearance area\n1. Please move robot to an open area and restart the task.\n2. It is recommended to set the low area as a no-go zone to prevent robot from getting stuck.": "Робот застрял в зоне с низким просветом\n1. Переместите робота на свободное место и перезапустите задачу.\n2. Рекомендуем отметить этот низкий участок как запретную зону, чтобы робот больше не застревал.",
    "Robot slips on the carpet\n1. Please move robot away from the carpet and restart the task\n2. It is recommended to set the carpet as a no-go zone to prevent robot from getting stuck.": "Робот пробуксовывает на ковре\n1. Уберите робота с ковра и перезапустите задачу\n2. Рекомендуем отметить ковёр как запретную зону, чтобы робот больше не застревал.",
    "The washboard is not installed and the robot cannot return to the self-wash base. Please ensure that the washboard is installed and the clasps on both sides are tightly fastened.": "Скребковая панель не установлена, и робот не может вернуться на базу самоочистки. Убедитесь, что скребковая панель установлена, а защёлки с обеих сторон надёжно зафиксированы.",
    "Robot slips in the curtain area\n1. Please move robot away from the curtain area and restart the task.\n2. Robot cannot clean this curtain area. It is recommended to remove it.": "Робот пробуксовывает в зоне со шторами\n1. Уберите робота из зоны со шторами и перезапустите задачу.\n2. Робот не может убирать в этой зоне со шторами. Рекомендуем убрать её.",
    "The water level of the washboard is abnormal. Please clean it timely to avoid blockage. If the problem still cannot be solved, please contact customer service.": "Уровень воды в скребковой панели нарушен. Своевременно очищайте её, чтобы избежать засора. Если проблему не удаётся решить, обратитесь в службу поддержки.",
    "Insufficient water in the fresh tank, please add water. Otherwise, the robot will not return to the base to have the mop pad cleaned during the cleaning task.": "Недостаточно воды в баке для чистой воды, долейте воду. Иначе во время уборки робот не будет возвращаться на базу для очистки салфетки.",
    "1. Robot failed to position because the area under the furniture is uneven or has changed.\n2. Start the task or control the LDS to rise in an open area": "1. Роботу не удалось определить своё положение, потому что участок под мебелью неровный или изменился.\n2. Запустите задачу или поднимите лидар (LDS) на свободном месте",
    "### A new map has been generated\nMulti-floor maps that can be saved have reached the upper limit. You need to replace or discard map before using it.": "### Создана новая карта\nДостигнут предел количества сохраняемых карт для нескольких этажей. Перед использованием замените или удалите одну из карт.",
    "Please take out the box and empty it. Alternatively, you can move robot to the dock for mop-washing (this will also drain the used water).": "Извлеките контейнер и опорожните его. Также можно отправить робота на док-станцию для мойки салфеток (при этом сольётся и грязная вода).",
    "Slippery floor. Robot failed to get through obstacles. You can wait for robot to retry, or clear the water around it and resume the task.": "Скользкий пол. Роботу не удалось преодолеть препятствия. Можно подождать, пока робот повторит попытку, либо убрать воду вокруг и возобновить задачу.",
    "Please check whether the power is off or the power switch is on in your home, and re-plug both ends of the base station power supply.": "Проверьте, не отключено ли электричество и включён ли выключатель в доме, и переподключите оба конца кабеля питания базовой станции.",
    "The area has been hidden. To reuse it, please go to the specific map and click the gray area to manually recover the hidden area.": "Зона скрыта. Чтобы снова её использовать, откройте нужную карту и нажмите на серую область, чтобы вручную восстановить скрытую зону.",
    "Mop holder quantity/placement error in the dock. Please install the mop holder or adjust its placement to ensure proper cleaning.": "Неверное количество или размещение держателей салфеток в док-станции. Установите держатель салфеток или поправьте его положение для правильной уборки.",
    "### Resume Cleaning Mode\nThe robot will automatically resume unfinished cleaning tasks after charging its battery to 80%.": "### Режим продолжения уборки\nРобот автоматически продолжит незавершённую уборку после зарядки аккумулятора до 80%.",
    "### Dust collecting (Auto-empty) task not performed\nThe robot will not perform auto-empty tasks during the DND period.": "### Сбор пыли (автоочистка) не выполняется\nРобот не выполняет автоочистку в режиме «Не беспокоить».",
    "The system detects that the upper cover of auto-empty base is not closed, or the dust collection bag is not installed.": "Система обнаружила, что верхняя крышка базы автоочистки не закрыта или не установлен мешок для пыли.",
    "The mop pad is out of place. Retry after putting it into the base station or install it onto the robot manually.": "Салфетка смещена. Повторите попытку, поместив её в базовую станцию или установив на робота вручную.",
    "A carpet is detected under the robot when it is mopping. Please move the robot to another place and restart it.": "Под роботом во время влажной уборки обнаружен ковёр. Переместите робота в другое место и перезапустите его.",
    "If so, replace the bag. Please clean the auto-empty vents of the dust bin and the base station regularly.": "Если да, замените мешок. Регулярно очищайте вентиляционные отверстия автоочистки у контейнера для пыли и базовой станции.",
    "The water in the clean water tank is about to be used up. Check and fill the clean water tank promptly.": "Вода в баке для чистой воды почти закончилась. Своевременно проверьте и долейте воду в бак для чистой воды.",
    "Chassis lift malfunction. Please restart the task. If the issue persists, contact customer service.": "Сбой подъёмного механизма шасси. Перезапустите задачу. Если проблема не исчезла, обратитесь в службу поддержки.",
    "Please make sure that the used water tank of robot is installed properly, and then start the task.": "Убедитесь, что бак для грязной воды робота установлен правильно, и затем запустите задачу.",
    "Check whether there is any object stuck in the main wheels and start the robot in a new position.": "Проверьте, не застрял ли посторонний предмет в основных колёсах, и запустите робота на новом месте.",
    "The charging dock is not powered on. Please check whether the power cord is plugged in correctly.": "Док-станция для зарядки не включена. Проверьте, правильно ли подключён кабель питания.",
    "Please ensure that all doors in the home are open and clear any obstacles around the vacuum-mop.": "Убедитесь, что все двери в доме открыты, и уберите препятствия вокруг робота-пылесоса.",
    "The upper cover of auto-empty base is not closed, or the dust collection bag is not installed.": "Верхняя крышка базы автоочистки не закрыта или не установлен мешок для пыли.",
    "Check if the mop pad is in the base station, or install the mop pad onto the robot manually.": "Проверьте, находится ли салфетка в базовой станции, либо установите салфетку на робота вручную.",
    "It is recommended to set passable thresholds if there are no Easy-to-Fall ramps on the path.": "Рекомендуем отметить пороги как проходимые, если на пути нет спусков с риском падения.",
    "Please ensure that all doors in the home are open and clear any obstacles along the path.": "Убедитесь, что все двери в доме открыты, и уберите препятствия с пути.",
    "Please clear any debris around the LDS and move robot to an open area to resume the task.": "Уберите мусор вокруг лидара (LDS) и переместите робота на свободное место, чтобы возобновить задачу.",
    "Please confirm the roller mop is properly installed before starting or resuming the task.": "Убедитесь, что валиковая салфетка установлена правильно, прежде чем запускать или возобновлять задачу.",
    "### The robot is in the DND period\nRobot will resume cleaning after the DND period ends.": "### Робот в режиме «Не беспокоить»\nРобот продолжит уборку после окончания режима «Не беспокоить».",
    "The system detects that the dust collection bag is full, or the air duct is blocked.": "Система обнаружила, что мешок для пыли заполнен или засорён воздуховод.",
    "Please use a dry cloth to wipe charging contacts of the robot and auto-empty base.": "Протрите сухой тканью контакты зарядки робота и базы автоочистки.",
    "### A new map has been generated\nYou need to save or discard map before using it.": "### Создана новая карта\nПеред использованием сохраните или удалите карту.",
    "Check whether the dirty water tank is full and the dirty water tank is installed.": "Проверьте, не заполнен ли бак для грязной воды и установлен ли он.",
    "Please try to delete the restricted area or move the vacuum-mop out of this area.": "Попробуйте удалить запретную зону или вывести робота-пылесоса из неё.",
    "The water level of the washboard is abnormal, please clean the washboard timely.": "Уровень воды в скребковой панели нарушен, своевременно очищайте её.",
    "There is no water in the clean water tank of the upper and lower water modules.": "Нет воды в баке для чистой воды модулей подачи и слива воды.",
    "Please ensure that no people or pets are on the path when restarting the task.": "Перед перезапуском задачи убедитесь, что на пути нет людей и животных.",
    "The robot's used water tank is too dirty. Please remove and clean it in time.": "Бак для грязной воды робота сильно загрязнён. Своевременно снимите и очистите его.",
    "The tank filter is worn out. Please replace it in time and reset the counter.": "Фильтр бака изношен. Своевременно замените его и сбросьте счётчик.",
    "The main brush is worn out. Please replace it in time and reset the counter.": "Основная щётка изношена. Своевременно замените её и сбросьте счётчик.",
    "The side brush is nearly worn out. Please replace it as soon as possible.": "Боковая щётка почти изношена. Замените её как можно скорее.",
    "Strong magnetic field detected. Please start away from the virtual wall.": "Обнаружено сильное магнитное поле. Запустите робота вдали от виртуальной стены.",
    "Please wipe the cliff sensor and start the cleanup away from the stairs.": "Протрите датчик перепада высот и запустите уборку вдали от лестницы.",
    "The robot is stuck, or its right wheel may be blocked by foreign objects": "Робот застрял, либо правое колесо заблокировано посторонними предметами",
    "The filter is worn out. Please replace it in time and reset the counter.": "Фильтр изношен. Своевременно замените его и сбросьте счётчик.",
    "The robot is stuck, or its left wheel may be blocked by foreign objects": "Робот застрял, либо левое колесо заблокировано посторонними предметами",
    "Hidden area. Please move the robot to the appropriate area and retry.": "Скрытая зона. Переместите робота в подходящую зону и повторите попытку.",
    "Please check for any obstacles in front of the robot and remove them.": "Проверьте, нет ли препятствий перед роботом, и уберите их.",
    "The side brush is worn out. Please replace it and reset the counter.": "Боковая щётка изношена. Замените её и сбросьте счётчик.",
    "Please check whether the laser distance sensor has any jammed items": "Проверьте, не застрял ли посторонний предмет в лазерном датчике расстояния",
    "Please clean the mop pad washboard in time to avoid stains or odor.": "Своевременно очищайте скребковую панель для салфеток, чтобы избежать пятен и запаха.",
    "Low water level in robot’s clean water box. Please refill promptly.": "Низкий уровень воды в баке для чистой воды робота. Своевременно долейте воду.",
    "The cleaning task is complete, please clean the mop pad washboard.": "Уборка завершена, очистите скребковую панель для салфеток.",
    "Edge mop not detected. Please install it before resuming cleaning.": "Краевая салфетка не обнаружена. Установите её перед возобновлением уборки.",
    "Used water tank deodorizer has been exhausted. Please replace it.": "Освежитель в баке для грязной воды закончился. Замените его.",
    "Please check whether the filter has dried or needs to be cleaned.": "Проверьте, высох ли фильтр и не нужно ли его очистить.",
    "Please remove the main brush and clean its bristles and bearings.": "Снимите основную щётку и очистите её ворс и подшипники.",
    "Please check whether the filter has dried or needs to be cleaned": "Проверьте, высох ли фильтр и не нужно ли его очистить",
    "The detergent is about to be used up, please replace it in time.": "Моющее средство почти закончилось, своевременно замените его.",
    "Please replace the detergent cartridge it and reset the counter.": "Замените картридж с моющим средством и сбросьте счётчик.",
    "Please clean the onboard dirty water tank and reset the counter.": "Очистите встроенный бак для грязной воды и сбросьте счётчик.",
    "Please replace the silver ion sterilizer and reset the counter.": "Замените стерилизатор с ионами серебра и сбросьте счётчик.",
    "Please check whether the laser distance sensor bumper is jammed": "Проверьте, не заклинило ли бампер лазерного датчика расстояния",
    "Malfunction due to an internal error. Try to restart the robot.": "Сбой из-за внутренней ошибки. Попробуйте перезапустить робота.",
    "The tank filter is nearly worn out. Please replace it in time.": "Фильтр бака почти изношен. Своевременно замените его.",
    "The main brush is nearly worn out. Please replace it in time.": "Основная щётка почти изношена. Своевременно замените её.",
    "Used water tank deodorizer is running out. Please replace it.": "Освежитель в баке для грязной воды заканчивается. Замените его.",
    "Robot is stuck due to slipping. Please clean the main wheels.": "Робот застрял из-за пробуксовки. Очистите основные колёса.",
    "The mop pads come off, install them before resuming working.": "Салфетки отсоединились, установите их перед возобновлением работы.",
    "The robot may be blocked or stuck. Please clear surrounding.": "Робот, возможно, заблокирован или застрял. Уберите всё вокруг.",
    "Please check whether the power cord is plugged in correctly.": "Проверьте, правильно ли подключён кабель питания.",
    "Please wait until the battery temperature returns to normal.": "Подождите, пока температура аккумулятора вернётся к норме.",
    "The dust collection bag is full, or the air duct is blocked.": "Мешок для пыли заполнен или засорён воздуховод.",
    "Please clean the dirty water channel and reset the counter.": "Очистите канал грязной воды и сбросьте счётчик.",
    "Please remove obstacles from the path and restart the task.": "Уберите препятствия с пути и перезапустите задачу.",
    "Mopping completed. Please remove and clean the mop in time.": "Влажная уборка завершена. Своевременно снимите и очистите салфетку.",
    "Robot's used water box is full. Please empty it promptly.": "Бак для грязной воды робота заполнен. Своевременно опорожните его.",
    "Please move the robot to a level surface and start again.": "Переместите робота на ровную поверхность и запустите снова.",
    "The filter is nearly worn out. Please replace it in time.": "Фильтр почти изношен. Своевременно замените его.",
    "Please replace the scale inhibitor and reset the counter.": "Замените средство против накипи и сбросьте счётчик.",
    "The clean water tank is not installed, please install it.": "Бак для чистой воды не установлен, установите его.",
    "Please clean omnidirectional wheel and reset the counter.": "Очистите всенаправленное колесо и сбросьте счётчик.",
    "Please clean the used water tank and washboard in time.": "Своевременно очищайте бак для грязной воды и скребковую панель.",
    "Mop not detected. Please install and continue the task.": "Салфетка не обнаружена. Установите её и продолжите задачу.",
    "Please clean water outlet filter and reset the counter.": "Очистите фильтр на выходе воды и сбросьте счётчик.",
    "Please try to clean the 3D obstacle avoidance sensor.": "Попробуйте очистить датчик объезда препятствий 3D.",
    "Please move the robot away from the area and restart.": "Уберите робота из этой зоны и перезапустите.",
    "Please clean roller mop filter and reset the counter.": "Очистите фильтр валиковой салфетки и сбросьте счётчик.",
    "Please try to delete the restricted area in the path.": "Попробуйте удалить запретную зону на пути.",
    "Detected that the vacuum-mop is in a restricted area.": "Обнаружено, что робот-пылесос находится в запретной зоне.",
    "Failed to install mop pads. Please install manually.": "Не удалось установить салфетки. Установите их вручную.",
    "Please clean fluffing roller and reset the counter.": "Очистите ворсовый валик и сбросьте счётчик.",
    "Sewage pump error. Please contact customer service.": "Ошибка насоса грязной воды. Обратитесь в службу поддержки.",
    "The water level in the used water tank is too high.": "Уровень воды в баке для грязной воды слишком высокий.",
    "Abnormal water level in the robot's used water tank": "Нарушен уровень воды в баке для грязной воды робота",
    "The 3D obstacle avoidance sensor is malfunctioning.": "Датчик объезда препятствий 3D неисправен.",
    "Please replace the squeegee and reset the counter.": "Замените скребок и сбросьте счётчик.",
    "Please clean and gently tap the collision sensor.": "Очистите и слегка постучите по датчику столкновений.",
    "Please replace the mop pad and reset the counter.": "Замените салфетку и сбросьте счётчик.",
    "Please wipe the optical sensor clean and restart.": "Протрите оптический датчик и перезапустите.",
    "Robot has detected Easy-to-Fall ramps on the path": "Робот обнаружил спуски с риском падения на пути",
    "Please check if the retractable legs are tangled.": "Проверьте, не намоталось ли что-то на выдвижные опоры.",
    "Cleanup route is blocked, returning to the dock.": "Маршрут уборки заблокирован, робот возвращается на док-станцию.",
    "Please replace the silver ion sterilizer timely.": "Своевременно замените стерилизатор с ионами серебра.",
    "The mop pad comes off during the cleaning task.": "Салфетка отсоединилась во время уборки.",
    "The mop pad has stopped rotating, please check.": "Салфетка перестала вращаться, проверьте.",
    "Move robot to an open area and resume the task.": "Переместите робота на свободное место и возобновите задачу.",
    "Check whether the dust collection bag is full.": "Проверьте, не заполнен ли мешок для пыли.",
    "Used water tank deodorizer has been exhausted.": "Освежитель в баке для грязной воды закончился.",
    "Please check if the mop is installed properly.": "Проверьте, правильно ли установлена салфетка.",
    "Please clean the sensors and reset the counter": "Очистите датчики и сбросьте счётчик",
    "The used water tank of robot is not installed.": "Бак для грязной воды робота не установлен.",
    "The dirty water tank is full or not installed.": "Бак для грязной воды заполнен или не установлен.",
    "Right wheel may be blocked by foreign objects": "Правое колесо, возможно, заблокировано посторонними предметами",
    "Edge sensor error. Please check and clean it.": "Ошибка краевого датчика. Проверьте и очистите его.",
    "Robot has detected people or pets on the path": "Робот обнаружил людей или животных на пути",
    "Please check if the used water tank is full.": "Проверьте, не заполнен ли бак для грязной воды.",
    "Please move the vacuum-mop out of this area.": "Выведите робота-пылесоса из этой зоны.",
    "Left wheel may be blocked by foreign objects": "Левое колесо, возможно, заблокировано посторонними предметами",
    "Abnormal water drainage from used water tank": "Нарушен слив воды из бака для грязной воды",
    "Onboard dirty water tank needs to be cleaned": "Встроенный бак для грязной воды нуждается в очистке",
    "Low water level in robot’s clean water box.": "Низкий уровень воды в баке для чистой воды робота.",
    "Silver Ion Sterilizer Near to Deterioration": "Стерилизатор с ионами серебра скоро придёт в негодность",
    "Please clean the visual positioning sensor.": "Очистите датчик визуального позиционирования.",
    "Used water tank deodorizer is running out.": "Освежитель в баке для грязной воды заканчивается.",
    "Please restart the robot and try it again.": "Перезапустите робота и попробуйте снова.",
    "Please replace the scale inhibitor timely.": "Своевременно замените средство против накипи.",
    "LDS cannot be raised here for positioning.": "Лидар (LDS) нельзя поднять здесь для позиционирования.",
    "Please start the robot in non-carpet area.": "Запустите робота на участке без ковра.",
    "Water level in the washboard is too high.": "Уровень воды в скребковой панели слишком высокий.",
    "Omnidirectional wheel needs to be cleaned": "Всенаправленное колесо нуждается в очистке",
    "The robot is stuck, or cannot go forward": "Робот застрял или не может ехать вперёд",
    "Battery level is too low. Please charge.": "Слишком низкий заряд аккумулятора. Поставьте на зарядку.",
    "The washboard is not installed properly.": "Скребковая панель установлена неправильно.",
    "Low water level in the clean water tank.": "Низкий уровень воды в баке для чистой воды.",
    "Robot has detected obstacles on the path": "Робот обнаружил препятствия на пути",
    "Please reposition the robot and restart.": "Переместите робота и перезапустите.",
    "The ultrasonic sensor is malfunctioning.": "Ультразвуковой датчик неисправен.",
    "Water outlet filter needs to be cleaned": "Фильтр на выходе воды нуждается в очистке",
    "Please remove and clean the side brush.": "Снимите и очистите боковую щётку.",
    "Dirty water channel needs to be cleaned": "Канал грязной воды нуждается в очистке",
    "Low battery. Robot will shut down soon.": "Низкий заряд. Робот скоро выключится.",
    "Please install the dust bin and filter.": "Установите контейнер для пыли и фильтр.",
    "Slippery floor. Please try again later.": "Скользкий пол. Повторите попытку позже.",
    "Washboard stops working. Please check.": "Скребковая панель перестала работать. Проверьте её.",
    "The clean water tank is not installed.": "Бак для чистой воды не установлен.",
    "Tank filter needs to be replaced soon": "Фильтр бака скоро потребует замены",
    "Please try to restart the vacuum-mop.": "Попробуйте перезапустить робота-пылесоса.",
    "Roller mop filter needs to be cleaned": "Фильтр валиковой салфетки нуждается в очистке",
    "No-Go zone or virtual wall detected.": "Обнаружена запретная зона или виртуальная стена.",
    "The detergent is about to be used up": "Моющее средство почти закончилось",
    "Side brush needs to be replaced soon": "Боковая щётка скоро потребует замены",
    "Main brush needs to be replaced soon": "Основная щётка скоро потребует замены",
    "The charging dock is not powered on": "Док-станция для зарядки не включена",
    "Fluffing roller needs to be cleaned": "Ворсовый валик нуждается в очистке",
    "Check mop Installation Instructions": "Ознакомьтесь с инструкцией по установке салфетки",
    "Please replace the squeegee timely.": "Своевременно замените скребок.",
    "Unable to reach the specified area.": "Не удаётся добраться до указанной зоны.",
    "Scale inhibitor has been exhausted": "Средство против накипи закончилось",
    "The robot is stuck, or cannot turn": "Робот застрял или не может повернуть",
    "Silver Ion Sterilizer Deteriorated": "Стерилизатор с ионами серебра пришёл в негодность",
    "The robot may be blocked or stuck.": "Робот, возможно, заблокирован или застрял.",
    "Please replace the mop pad timely.": "Своевременно замените салфетку.",
    "Laser distance sensor bumper error": "Ошибка бампера лазерного датчика расстояния",
    "Please fill the clean water tank.": "Наполните бак для чистой воды.",
    "Retractable legs may be tangled.": "На выдвижные опоры, возможно, что-то намоталось.",
    "Filter needs to be replaced soon": "Фильтр скоро потребует замены",
    "Visual positioning sensor error": "Ошибка датчика визуального позиционирования",
    "Please install the water tank.": "Установите бак для воды.",
    "Robot is stuck due to slipping": "Робот застрял из-за пробуксовки",
    "Strong magnetic field detected": "Обнаружено сильное магнитное поле",
    "Scale inhibitor is running out": "Средство против накипи заканчивается",
    "Mop holder error in the dock.": "Ошибка держателя салфеток в док-станции.",
    "Please will up the water tank": "Наполните бак для воды",
    "The filter not dry or blocked": "Фильтр не высох или засорён",
    "Base station not powered on.": "Базовая станция не включена.",
    "Tank filter must be replaced": "Фильтр бака необходимо заменить",
    "Mop pad installation failed.": "Не удалось установить салфетку.",
    "Dirty water tank pump error.": "Ошибка насоса бака для грязной воды.",
    "Failed to return to charge.": "Не удалось вернуться на зарядку.",
    "Laser distance sensor error": "Ошибка лазерного датчика расстояния",
    "Main brush must be replaced": "Основную щётку необходимо заменить",
    "Side brush must be replaced": "Боковую щётку необходимо заменить",
    "Failed to lift LDS module.": "Не удалось поднять модуль лидара (LDS).",
    "Edge mop stopped rotating.": "Краевая салфетка перестала вращаться.",
    "Chassis lift malfunction.": "Сбой подъёмного механизма шасси.",
    "Collision sensor is stuck": "Датчик столкновений заклинило",
    "Right magnet sensor error": "Ошибка правого магнитного датчика",
    "Cleanup route is blocked.": "Маршрут уборки заблокирован.",
    "Battery temperature error": "Ошибка температуры аккумулятора",
    "Dirty water tank blocked.": "Бак для грязной воды засорён.",
    "Failed to wash dirty mop.": "Не удалось вымыть грязную салфетку.",
    "Optical flow sensor error": "Ошибка датчика оптического потока",
    "Robot blocked by obstacle": "Робот заблокирован препятствием",
    "Left magnet sensor error": "Ошибка левого магнитного датчика",
    "Infrared shielding error": "Ошибка инфракрасной защиты",
    "Water tank not installed": "Бак для воды не установлен",
    "Squeegee Nearly Worn Out": "Скребок почти изношен",
    "The detergent is used up": "Моющее средство закончилось",
    "Mop Pad Stops Rotating.": "Салфетка перестала вращаться.",
    "Mop Pad Nearly Worn Out": "Салфетка почти изношена",
    "Filter must be replaced": "Фильтр необходимо заменить",
    "Sensors must be cleaned": "Датчики необходимо очистить",
    "### Drainage completed": "### Слив воды завершён",
    "Dust bin not installed": "Контейнер для пыли не установлен",
    "Fan speed sensor error": "Ошибка датчика скорости вентилятора",
    "The main brush wrapped": "На основную щётку что-то намоталось",
    "The side brush wrapped": "На боковую щётку что-то намоталось",
    "Fluffing Roller Error.": "Ошибка ворсового валика.",
    "### Cleanup completed": "### Уборка завершена",
    "Optical sensor error": "Ошибка оптического датчика",
    "Wheels are suspended": "Колёса висят в воздухе",
    "Accelerometer error": "Ошибка акселерометра",
    "Battery level error": "Ошибка уровня заряда аккумулятора",
    "### Drainage failed": "### Слив воды не выполнен",
    "Water tank is empty": "Бак для воды пуст",
    "The robot is stuck": "Робот застрял",
    "Cliff sensor error": "Ошибка датчика перепада высот",
    "Edge mop detached.": "Краевая салфетка отсоединилась.",
    "Self test failed.": "Самодиагностика не пройдена.",
    "Roller mop error.": "Ошибка валиковой салфетки.",
    "Flow sensor error": "Ошибка датчика потока",
    "Mop Not Installed": "Салфетка не установлена",
    "Edge sensor error": "Ошибка краевого датчика",
    "Move sensor error": "Ошибка датчика движения",
    "Squeegee Worn Out": "Скребок изношен",
    "Mop not detected.": "Салфетка не обнаружена.",
    "Water pump error": "Ошибка водяного насоса",
    "Mop cover error.": "Ошибка крышки салфетки.",
    "Cannot find base": "Не удаётся найти базу",
    "Mop Pad Worn Out": "Салфетка изношена",
    "Robot is tilted": "Робот наклонён",
    "Internal Error": "Внутренняя ошибка",
    "Charging error": "Ошибка зарядки",
    "Infrared error": "Ошибка инфракрасного датчика",
    "Internal error": "Внутренняя ошибка",
    "Camera error": "Ошибка камеры",
    "information": "информация",
    "Low battery": "Низкий заряд аккумулятора",
    "Gyro error": "Ошибка гироскопа",
    "consumable": "расходник",
    "Dock Error": "Ошибка док-станции",
    "RTC error": "Ошибка часов реального времени",
    "No error": "Нет ошибок",
    "warning": "предупреждение",
    "error": "ошибка",
}

# Longest keys first so a long description is replaced before any shorter
# substring of it.
_KEYS = sorted(TRANSLATIONS, key=len, reverse=True)


def translate_notification(content):
    """Return notification text with known English fragments replaced by Russian."""
    if not content or not isinstance(content, str):
        return content
    out = content
    for en in _KEYS:
        if en in out:
            out = out.replace(en, TRANSLATIONS[en])
    return out
